/**
 * Generated by scripts/optimise-images.py. Do not edit by hand.
 *
 * Maps each optimised source image to the responsive WebP widths that exist for
 * it on disk, so components/content/site-image.tsx can write a srcset that only
 * references files that were actually produced.
 */
export interface ImageVariants {
  width: number;
  height: number;
  widths: number[];
}

export const imageManifest: Record<string, ImageVariants> = {
  'Video-Surveillance-Dashboard': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'Virtual-Patrolling-System-1': { width: 1000, height: 563, widths: [640, 960, 1000] },
  'Virtual-Patrolling-System-2': { width: 1000, height: 563, widths: [640, 960, 1000] },
  'after-hours-security-monitoring': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'ai-perimeter-security': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'ai-security-for-construction-sites': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-education-facilities': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-healthcare': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-manufacturing': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-property-management': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-retail': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-security-for-warehouses': { width: 1600, height: 900, widths: [640, 960, 1280, 1600] },
  'ai-theft-detection': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'ai-video-analytics-architecture': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'cloud-video-backup-and-retention-management': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'guard-tour-verification': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'how-it-works-Step-1': { width: 1000, height: 563, widths: [640, 960, 1000] },
  'how-it-works-Step-2': { width: 1000, height: 563, widths: [640, 960, 1000] },
  'incident-investigation': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'license-and-instance-management': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'live-camera-streaming': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'loading-dock-security': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'mobile-access': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'motion-detection-1': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'multi-site-video-surveillance': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'night-security': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'parking-lot-surveillance': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'permission-group': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'product-configuration-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-configuration-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-dashboard-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-dashboard-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-license-plan-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-license-plan-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-live-streaming-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-live-streaming-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-notifications-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-notifications-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-user-management-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-user-management-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-video-backup-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-video-backup-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-virtual-patrolling-dark': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'product-virtual-patrolling-light': { width: 1600, height: 1224, widths: [640, 960, 1280, 1600] },
  'remote-site-monitoring': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'security-alert-management': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'security-system-user-management': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'trespassing-detection': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'unauthorized-access-detection': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'vandalism-prevention': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'vehicle-monitoring': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'video-surveillance-analytics-and-reporting': { width: 1229, height: 692, widths: [640, 960, 1229] },
  'camzify-logo-dark': { width: 825, height: 192, widths: [300, 600] },
  'camzify-logo-light': { width: 825, height: 192, widths: [300, 600] },
};
