#!/usr/bin/env python3
"""
Generate responsive WebP variants for the site's photographic assets.

Why this exists: next.config.js sets `images: { unoptimized: true }`, which is
deliberate for the deploy target. The consequence is that next/image emits a plain
<img> with a single src and no srcset, so the `sizes` attribute on those components
does nothing and a phone downloads the same 1600px file as a desktop. Measured on the
heaviest hero: 619 KB delivered to every device, where 640px WebP is 65 KB.

So the variants are produced here, checked into the repo, and served by
components/content/site-image.tsx, which writes a real srcset. No build-time image
service and no host-specific optimiser is involved, so this survives a change of
deploy target.

WebP with no JPEG fallback is deliberate: support is universal across browsers still
receiving security updates, and a <picture> with two sources would double the variant
count for no reachable audience.

Run:  python3 scripts/optimise-images.py
It is idempotent — existing variants are overwritten, and sources are left in place.
"""
import os, glob, sys
from PIL import Image

WIDTHS = [640, 960, 1280, 1600]
QUALITY = 82
MIN_BYTES = 60 * 1024  # below this a variant ladder costs more in complexity than it saves

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    pub = os.path.join(root, 'public')
    sources = sorted(glob.glob(os.path.join(pub, '*.jpg')))
    # The logo is a PNG with transparency, well under the size threshold, but it ships
    # in both theme variants on every page at 825px wide for a ~150px display. WebP
    # keeps the alpha channel and a narrower ladder removes the rest of the waste.
    sources += sorted(glob.glob(os.path.join(pub, 'camzify-logo-*.png')))
    before = after = 0
    converted = []

    for src in sources:
        size = os.path.getsize(src)
        is_logo = os.path.basename(src).startswith('camzify-logo-')
        if size < MIN_BYTES and not is_logo:
            continue
        # RGBA for the logo so transparency survives; RGB for photographs.
        im = Image.open(src)
        im = im.convert('RGBA') if is_logo else im.convert('RGB')
        stem = os.path.splitext(os.path.basename(src))[0]
        ladder = [300, 600] if is_logo else WIDTHS
        widths = [w for w in ladder if w < im.width] + ([im.width] if not is_logo else [])
        widths = widths or [im.width]
        before += size
        for w in widths:
            out = os.path.join(pub, f'{stem}-{w}.webp')
            resized = im if w == im.width else im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
            resized.save(out, 'WEBP', quality=QUALITY, method=6)
            after += os.path.getsize(out)
        converted.append((stem, im.width, im.height, widths))

    # The component cannot discover which widths exist at runtime, so the ladder is
    # written out as a typed manifest. Regenerating images regenerates this with them,
    # which is what stops a srcset pointing at a variant that was never produced.
    manifest = os.path.join(root, 'lib', 'image-manifest.ts')
    with open(manifest, 'w') as fh:
        fh.write('/**\n')
        fh.write(' * Generated by scripts/optimise-images.py. Do not edit by hand.\n')
        fh.write(' *\n')
        fh.write(' * Maps each optimised source image to the responsive WebP widths that exist for\n')
        fh.write(' * it on disk, so components/content/site-image.tsx can write a srcset that only\n')
        fh.write(' * references files that were actually produced.\n')
        fh.write(' */\n')
        fh.write('export interface ImageVariants {\n  width: number;\n  height: number;\n  widths: number[];\n}\n\n')
        fh.write('export const imageManifest: Record<string, ImageVariants> = {\n')
        for stem, w, h, widths in converted:
            fh.write(f"  '{stem}': {{ width: {w}, height: {h}, widths: [{', '.join(str(x) for x in widths)}] }},\n")
        fh.write('};\n')

    for stem, w, h, widths in converted:
        print(f'  {stem}  {w}x{h}  ->  {", ".join(str(x) for x in widths)}')
    print(f'\n{len(converted)} sources, {before/1048576:.1f} MB -> {after/1048576:.1f} MB across all variants')
    if not converted:
        print('nothing over the size threshold', file=sys.stderr)

if __name__ == '__main__':
    main()
