import NextImage from 'next/image';
import { imageManifest } from '@/lib/image-manifest';

/**
 * A photographic image with a real srcset.
 *
 * Drop-in for `next/image` at the call sites that render photos. It exists because
 * next.config.js sets `images: { unoptimized: true }`, which is deliberate for the
 * deploy target but means next/image emits one `src` and no srcset — so the `sizes`
 * attribute on those call sites was inert and every device downloaded the desktop
 * file. Measured on the heaviest hero: 619 KB to a phone that needed 65 KB.
 *
 * Responsive WebP variants are generated by scripts/optimise-images.py and listed in
 * lib/image-manifest.ts. This reads that manifest, so a srcset can only ever reference
 * a file that was actually produced. An image with no entry — a logo, an icon, anything
 * under the size threshold — falls through to next/image unchanged rather than being
 * silently broken.
 *
 * `priority` marks the LCP element: eager loading plus fetchPriority="high", and no
 * lazy attribute. Use it for the one image above the fold, not for every image on the
 * page; marking everything high priority is the same as marking nothing.
 */
export function SiteImage({
  src,
  alt,
  width,
  height,
  className = '',
  sizes = '100vw',
  priority = false,
  'aria-hidden': ariaHidden,
}: {
  /** Path under /public, e.g. "/ai-security-for-warehouses.jpg". */
  src: string;
  alt: string;
  width: number;
  height: number;
  className?: string;
  sizes?: string;
  priority?: boolean;
  /**
   * Declared explicitly because this component does not spread rest props. Without it
   * a caller could pass aria-hidden and have it silently dropped — which is exactly
   * what happened to the duplicate theme variant of the site logo.
   */
  'aria-hidden'?: boolean | 'true' | 'false';
}) {
  const stem = src.replace(/^\//, '').replace(/\.(jpg|jpeg|png)$/i, '');
  const variants = imageManifest[stem];

  if (!variants) {
    return (
      <NextImage
        src={src}
        alt={alt}
        width={width}
        height={height}
        className={className}
        sizes={sizes}
        priority={priority}
        aria-hidden={ariaHidden}
      />
    );
  }

  const srcSet = variants.widths.map((w) => `/${stem}-${w}.webp ${w}w`).join(', ');
  const fallback = `/${stem}-${variants.widths[variants.widths.length - 1]}.webp`;

  // A raw <img> rather than next/image: the whole point is the srcset below, which
  // next/image will not emit while images.unoptimized is set.
  return (
    <img
      src={fallback}
      srcSet={srcSet}
      sizes={sizes}
      alt={alt}
      width={width}
      height={height}
      className={className}
      aria-hidden={ariaHidden}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : 'auto'}
      decoding={priority ? 'sync' : 'async'}
    />
  );
}
