import { generatePageMeta } from '@/lib/page-utils';
import { PageShell } from '@/components/layout/page-shell';
import { FaqSection } from '@/components/content/faq-section';
import { siteConfig } from '@/lib/site-config';
import Link from 'next/link';

/**
 * Page identity. Declared once and consumed twice: by `generatePageMeta` for the
 * <head> tags, and by `PageShell` for the on-page structured data.
 *
 * States what the site does, checked in code on 2026-09-07, and what it does not yet
 * do. No conformance level is claimed, because none has been audited.
 */
const pageMeta = {
  title: "Accessibility",
  description: "How the Camzify website is built to be usable with a keyboard, a screen reader, reduced motion and either theme, what is not yet right, and how to tell us when something is in your way.",
  path: "/accessibility",
};

export const metadata = generatePageMeta({ ...pageMeta });

const UPDATED = '7 September 2026';

const faqs = [
  { question: 'Does the site meet WCAG 2.1 AA?', answer: 'We build to it and check the things we can check in code, but no independent audit has been done, so we do not claim conformance. This page says what is in place and what is not, which is more useful than a badge.' },
  { question: 'Can I use the site without a mouse?', answer: 'Yes. Every link, button, menu and form control is reachable with Tab and operable with Enter or Space, focus is visible, and the navigation menus open on keyboard focus. The interactive patrol demonstration can be operated entirely from the keyboard.' },
  { question: 'I have motion sensitivity. Does the site animate?', answer: 'It respects the reduced-motion setting in your operating system or browser. With it on, the homepage patrol animation holds on one frame, section reveals appear without movement, and the pulsing indicators stop.' },
  { question: 'Something is in my way. What do I do?', answer: 'Email us at the address on this page with the page and what happened. We treat accessibility reports as bugs and fix them in the site itself, not with a workaround.' },
];

const done = [
  'Every page has one heading that names it, followed by section headings in order, so a screen reader can outline it.',
  'Every link, button, menu and form control works from the keyboard, with a visible focus ring in both themes.',
  'Text and control colours are set as tokens for light and dark mode and checked for contrast in both; nothing depends on colour alone, and status is always also a word or an icon.',
  'Collapsed content such as FAQ answers and closed menus stays in the page and is marked inert, so it is not announced while closed and is still there for assistive technology when opened.',
  'Illustrations and product screenshots carry text descriptions; camera frames that are decorative are marked as such.',
  'The reduced-motion preference is honoured everywhere the site animates.',
  'Pages reflow to a phone width without horizontal scrolling and without content being cut off.',
];

const notYet = [
  'No independent audit against WCAG 2.1 has been carried out, so no conformance level is claimed.',
  'The patrol report PDFs produced by the product are generated by the console, not by this site; their accessibility is covered by the customer agreement, not this statement.',
  'Some section illustrations convey their meaning visually and are described in a caption rather than in full in alternative text.',
];

export default function AccessibilityPage() {
  return (
    <PageShell {...pageMeta} faqs={faqs} breadcrumbs={[{ label: 'Accessibility' }]} showCTA={false}>
      <section className="pb-16">
        <div className="mx-auto max-w-site px-6">
          <span className="font-mono text-mono-sm uppercase text-primary">Statement · last checked {UPDATED}</span>
          <h1 className="mt-3 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">Accessibility</h1>
          <p className="mt-6 max-w-prose text-body text-muted-foreground">
            <strong className="font-semibold text-foreground">We want anyone who evaluates security software to be able to read this site, whatever they use to browse.</strong>{' '}
            This statement says what is in place, what is not yet, and how to tell us when something is in your way. It does not claim a conformance level, because none has been independently audited.
          </p>

          <h2 className="mt-12 font-display text-2xl font-bold">What is in place</h2>
          <ul className="mt-4 max-w-prose space-y-3 text-muted-foreground">
            {done.map((d) => (
              <li key={d} className="flex gap-3"><span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-live" />{d}</li>
            ))}
          </ul>

          <h2 className="mt-12 font-display text-2xl font-bold">What is not yet right</h2>
          <ul className="mt-4 max-w-prose space-y-3 text-muted-foreground">
            {notYet.map((d) => (
              <li key={d} className="flex gap-3"><span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-warn" />{d}</li>
            ))}
          </ul>

          <h2 className="mt-12 font-display text-2xl font-bold">Tell us</h2>
          <p className="mt-4 max-w-prose text-muted-foreground">
            If a page, a control or a document is in your way, email{' '}
            <a href={`mailto:${siteConfig.email}`} className="text-primary hover:underline">{siteConfig.email}</a> with the page address and what happened. We treat these reports as defects in the site and fix them there. The{' '}
            <Link href="/contact" className="text-primary hover:underline">contact page</Link> also has a form and a telephone number.
          </p>
        </div>
      </section>

      <FaqSection items={faqs} />
    </PageShell>
  );
}
